on: [push]
name: CI/CD
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:6
        ports:
          - 6379/tcp

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Install Racket
      uses: Bogdanp/setup-racket@master
      with:
        variant: CS
        version: stable

    - name: Install pkg and deps
      run: raco pkg install --batch --auto

    - name: Run tests
      run: raco test session
      env:
        REDIS_URL: redis://127.0.0.1:${{ job.services.redis.ports[6379] }}/0
